import prisma from "../../prisma/prisma";

const indianCities = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Kolkata",
  "Chennai",
  "Hyderabad",
  "Ahmedabad",
  "Pune",
  "Surat",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri-Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Coimbatore",
  "Agra",
  "Madurai",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Howrah",
  "Ranchi",
  "Gwalior",
  "Jabalpur",
  "Vijayawada",
  "Jodhpur",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Thiruvananthapuram",
  "Solapur",
  "Tiruchirappalli",
  "Bareilly",
  "Moradabad",
];

const hospitalNames = [
  "Apollo Hospitals",
  "Fortis Healthcare",
  "AIIMS (All India Institute of Medical Sciences)",
  "Max Healthcare",
  "Manipal Hospitals",
  "Narayana Health",
  "Columbia Asia Hospitals",
  "Medanta - The Medicity",
  "Artemis Hospitals",
  "Kokilaben Dhirubhai Ambani Hospital",
  "Sir Ganga Ram Hospital",
  "Tata Memorial Hospital",
  "Lilavati Hospital",
  "Wockhardt Hospitals",
  "Aster Medcity",
  "KIMS (Krishna Institute of Medical Sciences)",
  "Nanavati Super Speciality Hospital",
  "Moolchand Hospital",
  "Sankara Nethralaya",
  "Ruby Hall Clinic",
  "Kerala Institute of Medical Sciences (KIMS)",
  "Christian Medical College (CMC), Vellore",
  "Asian Heart Institute",
  "Yashoda Hospitals",
  "PGIMER (Postgraduate Institute of Medical Education and Research)",
  "Rajiv Gandhi Cancer Institute & Research Centre",
  "Amrita Institute of Medical Sciences",
  "Sri Ramachandra Medical Centre",
  "Manipal Hospitals",
  "Sir H.N. Reliance Foundation Hospital and Research Centre",
  "Indraprastha Apollo Hospitals",
  "Aditya Birla Memorial Hospital",
  "P. D. Hinduja Hospital",
  "Tata Main Hospital",
  "Global Hospitals",
  "NIMHANS (National Institute of Mental Health and Neurosciences)",
  "Jaslok Hospital",
  "Rajkumari Amrit Kaur College of Nursing",
  "Tata Memorial Centre",
  "Sahyadri Hospitals",
  "MIOT International",
  "Kokilaben Dhirubhai Ambani Hospital and Medical Research Institute",
  "Apollo Gleneagles Hospitals",
  "Hiranandani Hospital",
  "P. D. Hinduja National Hospital and Medical Research Centre",
  "Breach Candy Hospital",
  "King Edward Memorial Hospital",
  "CARE Hospitals",
  "L.V. Prasad Eye Institute",
  "Pune Institute of Computer Technology (PICT)",
  "Unity Hospital",
  "City General Hospital",
  "Central Medical Center",
  "Grandview Hospital",
  "Maplewood Clinic",
  "Riverside Medical Center",
  "Pineview Hospital",
  "Oakridge Medical Center",
  "Sunset Healthcare",
  "Golden State Hospital",
  "Lakeview Medical Center",
  "Valley Health Clinic",
  "Mount Sinai Hospital",
  "Evergreen Medical Center",
  "Fairview General Hospital",
  "Meadowbrook Clinic",
  "Parkside Hospital",
  "Liberty Medical Center",
  "Cypress Hill Hospital",
  "Bayside Healthcare",
  "Harborview Medical Center",
  "Palmview Hospital",
  "Greenwood Clinic",
  "Highland General Hospital",
  "Rosewood Medical Center",
  "Sunshine Hospital",
  "Windsor Health Clinic",
  "Hillcrest Hospital",
  "Cedarview Medical Center",
  "Hope Medical Center",
  "Aspen Hills Hospital",
  "Prairieview Clinic",
  "Ridgeview Hospital",
  "Willowbrook Medical Center",
  "Sunnyvale Healthcare",
  "Holly Medical Center",
  "Bayview General Hospital",
  "Lakefront Clinic",
  "Gardenview Hospital",
  "Mountain Health Center",
  "Magnolia Hospital",
  "Pinecrest Medical Center",
  "Everest Clinic",
  "Haven Hospital",
  "Greenleaf Medical Center",
  "Oakhurst Healthcare",
  "Valleyview Hospital",
  "Cypress Creek Clinic",
  "Meadowview Hospital",
  "Maple Grove Medical Center",
  "Fairfield General Hospital",
  "Lakeside Clinic",
  "Heritage Medical Center",
  "Sycamore Hill Hospital",
  "Rosehill Healthcare",
  "Sunnybrook Medical Center",
  "Woodland Health Clinic",
  "Chestnut Hospital",
  "Oakwood Medical Center",
  "Willow Grove Clinic",
  "Parkview Hospital",
  "Meadowlark General Hospital",
  "Sunset Medical Center",
  "Mountainview Healthcare",
  "Prairie Hill Hospital",
  "Valleycrest Medical Center",
  "Cypress Springs Clinic",
  "Harmony Hospital",
  "Greenfield Medical Center",
  "Palm Grove Healthcare",
  "Hillside Hospital",
  "Cedarwood Clinic",
  "Oceanside General Hospital",
  "Garden Grove Medical Center",
  "Evergreen Clinic",
  "Birchwood Hospital",
  "Waterside Medical Center",
  "Golden Valley Healthcare",
  "Meadowbrook General Hospital",
  "Riverside Medical Center",
  "Sunrise Hospital",
  "Lakefront Clinic",
  "Mapleview Hospital",
  "Pinehill Medical Center",
  "Oakleaf Healthcare",
  "Sycamore Creek Hospital",
  "Valleyview Medical Center",
  "Cypress Hills Clinic",
  "Fairway Hospital",
  "Lakeside Medical Center",
  "Heritage Health Clinic",
  "Rosewood Hospital",
  "Sunnyside Healthcare",
  "Woodland Medical Center",
  "Chestnut Grove Hospital",
  "Oakview Clinic",
  "Willow Creek Hospital",
  "Parkside General Hospital",
  "Meadowland Clinic",
  "Sunset Healthcare",
  "Mountainview Medical Center",
  "Prairie Hill Clinic",
  "Valleycrest Hospital",
  "Cypress Springs Medical Center",
  "Harmony Clinic",
  "Greenfield Hospital",
  "Palm Grove Medical Center",
  "Hillside Health Clinic",
  "Cedarwood Hospital",
  "Oceanside Medical Center",
  "Garden Grove Clinic",
  "Evergreen Hospital",
  "Birchwood Medical Center",
  "Waterside Clinic",
  "Golden Valley Hospital",
  "Meadowbrook Healthcare",
  "Riverside General Hospital",
  "Sunrise Medical Center",
  "Lakeview Clinic",
  "Maplewood Hospital",
  "Pineview Clinic",
  "Oakridge Hospital",
  "Sunnyvale Medical Center",
  "Golden State Clinic",
  "Lakefront Hospital",
  "Valley Health Center",
  "Mount Sinai Clinic",
  "Evergreen Hospital",
  "Fairview Medical Center",
  "Meadowbrook Hospital",
  "Parkside Clinic",
  "Liberty General Hospital",
  "Cypress Hill Clinic",
  "Bayside Medical Center",
  "Harborview Clinic",
  "Palmview General Hospital",
  "Greenwood Medical Center",
  "Highland Healthcare",
  "Rosewood General Hospital",
  "Sunshine Clinic",
  "Windsor Hospital",
  "Hillcrest Medical Center",
  "Cedarview General Hospital",
  "Hope Clinic",
  "Aspen Hills Medical Center",
  "Prairieview Hospital",
  "Ridgeview Clinic",
  "Willowbrook Hospital",
  "Sunnyvale Health Clinic",
  "Holly Hospital",
  "Bayview Medical Center",
  "Lakefront Clinic",
  "Gardenview Hospital",
  "Mountain Health Center",
  "Magnolia Medical Center",
  "Pinecrest General Hospital",
  "Everest Clinic",
  "Haven Medical Center",
  "Greenleaf Hospital",
  "Oakhurst Clinic",
  "Valleyview Hospital",
  "Cypress Creek General Hospital",
  "Meadowview Clinic",
  "Maple Grove Hospital",
  "Fairfield Medical Center",
  "Lakeside Clinic",
  "Heritage General Hospital",
  "Sycamore Hill Clinic",
  "Rosehill Hospital",
  "Sunnybrook Healthcare",
  "Woodland Medical Center",
  "Chestnut Hospital",
  "Oakwood Clinic",
  "Willow Grove General Hospital",
  "Parkview Medical Center",
  "Meadowlark Clinic",
  "Sunset Hospital",
  "Mountainview Medical Center",
  "Prairie Hill Clinic",
  "Valleycrest Hospital",
  "Cypress Springs Healthcare",
  "Harmony General Hospital",
  "Greenfield Clinic",
  "Palm Grove Hospital",
  "Hillside Medical Center",
  "Cedarwood Clinic",
  "Oceanside General Hospital",
  "Garden Grove Medical Center",
  "Evergreen Clinic",
  "Birchwood Hospital",
  "Waterside Medical Center",
  "Golden Valley Healthcare",
  "Meadowbrook General Hospital",
  "Riverside Medical Center",
  "Sunrise Hospital",
  "Lakefront Clinic",
  "Mapleview Hospital",
  "Pinehill Medical Center",
  "Oakleaf Healthcare",
  "Sycamore Creek Hospital",
  "Valleyview Medical Center",
  "Cypress Hills Clinic",
  "Fairway Hospital",
  "Lakeside Medical Center",
  "Heritage Health Clinic",
  "Rosewood Hospital",
  "Sunnyside Healthcare",
  "Woodland Medical Center",
  "Chestnut Grove Hospital",
  "Oakview Clinic",
  "Willow Creek Hospital",
  "Parkside General Hospital",
  "Meadowland Clinic",
  "Sunset Healthcare",
  "Mountainview Medical Center",
  "Prairie Hill Clinic",
  "Valleycrest Hospital",
  "Cypress Springs Medical Center",
  "Harmony Clinic",
  "Greenfield Hospital",
  "Palm Grove Medical Center",
  "Hillside Health Clinic",
  "Cedarwood Hospital",
  "Oceanside Medical Center",
  "Garden Grove Clinic",
  "Evergreen Hospital",
  "Birchwood Medical Center",
  "Waterside Clinic",
  "Golden Valley Hospital",
  "Meadowbrook Healthcare",
  "Riverside General Hospital",
  "Sunrise Medical Center",
  "Lakeview Clinic",
  "Maplewood Hospital",
  "Pineview Clinic",
  "Oakridge Hospital",
  "Sunnyvale Medical Center",
  "Golden State Clinic",
  "Lakefront Hospital",
  "Valley Health Center",
  "Mount Sinai Clinic",
  "Evergreen Hospital",
  "Fairview Medical Center",
  "Meadowbrook Hospital",
  "Parkside Clinic",
  "Liberty General Hospital",
  "Cypress Hill Clinic",
  "Bayside Medical Center",
  "Harborview Clinic",
  "Palmview General Hospital",
  "Greenwood Medical Center",
  "Highland Healthcare",
  "Rosewood General Hospital",
  "Sunshine Clinic",
  "Windsor Hospital",
  "Hillcrest Medical Center",
  "Cedarview General Hospital",
  "Hope Clinic",
  "Aspen Hills Medical Center",
  "Prairieview Hospital",
  "Ridgeview Clinic",
  "Willowbrook Hospital",
  "Sunnyvale Health Clinic",
  "Holly Hospital",
  "Bayview Medical Center",
  "Lakefront Clinic",
  "Gardenview Hospital",
  "Mountain Health Center",
  "Magnolia Medical Center",
  "Pinecrest General Hospital",
  "Everest Clinic",
  "Haven Medical Center",
  "Greenleaf Hospital",
  "Oakhurst Clinic",
  "Valleyview Hospital",
  "Cypress Creek General Hospital",
  "Meadowview Clinic",
  "Maple Grove Hospital",
  "Fairfield Medical Center",
  "Lakeside Clinic",
  "Heritage General Hospital",
  "Sycamore Hill Clinic",
  "Rosehill Hospital",
  "Sunnybrook Healthcare",
  "Woodland Medical Center",
  "Chestnut Hospital",
  "Oakwood Clinic",
  "Willow Grove General Hospital",
  "Parkview Medical Center",
  "Meadowlark Clinic",
  "Sunset Hospital",
  "Mountainview Medical Center",
  "Prairie Hill Clinic",
  "Valleycrest Hospital",
  "Cypress Springs Healthcare",
  "Harmony General Hospital",
  "Greenfield Clinic",
  "Palm Grove Hospital",
  "Hillside Medical Center",
  "Cedarwood Clinic",
  "Oceanside General Hospital",
  "Garden Grove Medical Center",
  "Evergreen Clinic",
  "Birchwood Hospital",
  "Waterside Medical Center",
  "Golden Valley Healthcare",
  "Meadowbrook General Hospital",
  "Riverside Medical Center",
  "Sunrise Hospital",
  "Lakefront Clinic",
  "Mapleview Hospital",
  "Pinehill Medical Center",
  "Oakleaf Healthcare",
  "Sycamore Creek Hospital",
  "Valleyview Medical Center",
  "Cypress Hills Clinic",
  "Fairway Hospital",
  "Lakeside Medical Center",
  "Heritage Health Clinic",
  "Rosewood Hospital",
  "Sunnyside Healthcare",
  "Woodland Medical Center",
  "Chestnut Grove",
];

// console.log(indianCities);

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function generateVaccinationCenter(i) {
  const centerName = hospitalNames[i];
  const city = indianCities[getRandomInt(0, indianCities.length - 1)];
  const workingHours = `${getRandomInt(8, 12)}AM to ${getRandomInt(3, 8)}PM`;
  const slotsLeft = getRandomInt(0, 10);
  const covaxin = getRandomInt(0, 250);
  const covishield = getRandomInt(0, 400);
  const pfizer = getRandomInt(0, 30);

  return {
    centerName,
    city,
    workingHours,
    slotsLeft,
    covaxin,
    covishield,
    pfizer,
  };
}

export default async function handler(req, res) {
  try {
    for (let i = 0; i < hospitalNames.length; i++) {
      const vaccinationCenterData = generateVaccinationCenter(i);

      await prisma.vaccinationCenter.create({
        data: vaccinationCenterData,
      });
    }

    console.log("Data generation completed!");
    res.json({
      message: "maybe done",
    });
  } catch (error) {
    console.error("Error generating data:", error);
  }
}
